# Generated by Django 4.1.4 on 2022-12-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuits',
            name='circuits_Name',
            field=models.CharField(default='circuits Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuits_city',
            field=models.CharField(default='circuits city', max_length=256),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuits_laps',
            field=models.CharField(default='circuits laps', max_length=255),
        ),
        migrations.AlterField(
            model_name='circuits',
            name='circuits_length',
            field=models.CharField(default='circuits length', max_length=255),
        ),
    ]
